# Site settings
title: Kamil Ogórek – Senior Client-side Engineer
email: kamil.ogorek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Senior Client-side Engineer in X-Team. Ampersand.js core team member. Climber, weightlifter, drummer and music lover. I cook and admire great food.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kamilogorek.pl" # the base hostname & protocol for your site
twitter_username: kamilogorek
github_username: kamilogorek

# Build settings
markdown: kramdown
highlighter: pygments
