title: Kamil Ogórek
description: Software development passionate mainly focused on client-side technologies. Currently working as Software Engineer at Sentry. Weightlifter, powerlifter, training and nutrition geek.
author: Kamil Ogórek
url: https://kamilogorek.com
email: kamil.ogorek@gmail.com
theme: jekyll-whiteglass
permalink: /blog/:title

plugins:
  - jekyll-feed
  - jekyll-redirect-from

include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - node_modules

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

twitter_username: kamilogorek
twitter_image: assets/images/photo.jpg
github_username: kamilogorek
linkedin_username: kamilogorek
google_analytics: UA-29832978-1
