title: Kamil Ogórek
description: Software development passionate mainly focused on client-side technologies. Currently working as Lead Code Whisperer at Corgibytes. Weightlifter, powerlifter, training and nutrition geek.
author: Kamil Ogórek
url: https://kamilogorek.com
email: kamil.ogorek@gmail.com
theme: jekyll-whiteglass
permalink: /blog/:title

gems:
  - jekyll-feed
  - jekyll-redirect-from

include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - generate-cv.js
  - README.md

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post

twitter_username: kamilogorek
github_username:  kamilogorek
linkedin_username: kamilogorek
google_analytics: UA-29832978-1
